### ISSUE TITLE
Your WordPress.com/ Gravatar username

### ISSUE THREAD

**Issue by danielbachhuber** [AgencyPMG/SEO-Auto-Linker#14]
Hey Chris,

As a way of highlighting the plugins we've vetted, we're slowly rolling out a plugin directory on vip.wordpress.com. Here's the page we've created for your plugin: http://vip.wordpress.com/plugins/seo-auto-linker/

Do you have a WordPress.com / Gravatar username so we can show your name and avatar in the upper right?

Thanks,

Daniel

**Comment by chrisguitarguy** [comment]
Hi Daniel,

I guess this is my Gravatar profile: https://en.gravatar.com/bscout86  Does that work?

Thanks!
-CD

**Comment by danielbachhuber** [comment]
Yep, that's great. Thanks!
