### ISSUE TITLE
Site-wide blacklist broken

### ISSUE THREAD

**Issue by ckeboss** [AgencyPMG/SEO-Auto-Linker#3]
I fixed the issue in my fork, but haven't used GIT enough to figure out how to request a pull from one line, not sure if it's possible. But you had a misspelling of a variable. Reference https://github.com/ckeboss/SEO-Auto-Linker/commit/94e1ee5c85e519f6c8adfb1756f498c2fed4b6bc

**Comment by chrisguitarguy** [comment]
Fixed in master.
